using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using CW_Utils;

namespace CombatCommander {

	public enum ORDERS {
		ADVANCE,
		ARTILLERY_DENIED,
		ARTILLERY_REQUEST,
		COMMAND_CONFUSION,
		FIRE,
		MOVE,
		RECOVER,
		ROUT
	}

	public enum ACTIONS {
		AMBUSH,
		ASSAULT_FIRE,
		BORE_SIGHTING,
		COMMAND_CONFUSION,
		CONCEALMENT,
		CROSSFIRE,
		DEMOLITIONS,
		DIG_IN,
		OPPORTUNITY_FIRE,
		HAND_GRENADES,
		HIDDEN_ENTRENCHMENTS,
		HIDDEN_MINES,
		HIDDEN_PILLBOX,
		HIDDEN_UNIT,
		HIDDEN_WIRE,
		LIGHT_WOUNDS,
		MARKSMANSHIP,
		NO_QUARTER,
		SMOKE_GRENADES,
		SPRAY_FIRE,
		SUSTAINED_FIRE
	}

	public enum EVENTS {
		AIR_SUPPORT,
		BATTLE_HARDEN,
		BATTLEFIELD_INTEGRITY,
		BLAZE,
		BOOBY_TRAP,
		BREEZE,
		COMMAND_AND_CONTROL,
		COMMISSAR,
		COWER,
		DEPLOY,
		DUST,
		ELAN,
		ENTRENCH,
		FIELD_PROMOTION,
		FOG_OF_WAR,
		HERO,
		INFILTRATION,
		INTERDICTION,
		INTERROGATION,
		KIA,
		MALFUNCTION,
		MEDIC,
		MISSION_OBJECTIVE,
		PRISONERS_OF_WAR,
		RECONNAISSANCE,
		REINFORCEMENTS,
		RUBBLE,
		SAPPERS,
		SCROUNGE,
		SHELL_SHOCK,
		SHELLHOLES,
		STRATEGIC_OBJECTIVE,
		SUPPRESSING_FIRE,
		WALKING_WOUNDED,
		WHITE_PHOSPHORUS
	}

	public enum TRIGGERS {
		NONE,
		EVENT,
		JAMMED,
		SNIPER,
		TIME
	}

	public class Card {

		private Nationality _nation;
		private int _number;

		private ORDERS _order;
		private ACTIONS _action;
		private EVENTS _event;
		private String _hex;
		private int _white_die;
		private int _red_die;
		private TRIGGERS _trigger;

		public Card(Nationality nation, int number, ORDERS order, ACTIONS action, EVENTS ev, String hex, int white, int red, TRIGGERS trigger) {
			_nation = nation;
			_number = number;
			_order = order;
			_action = action;
			_event = ev;
			_hex = hex;
			_white_die = white;
			_red_die = red;
			_trigger = trigger;
		}

		public override string ToString() {
			return Nation.Abbrev.ToString() + "-" + Number.ToString("00");
		}
		public ACTIONS Action {
			get { return _action; }
		}
		public int DieRoll {
			get { return _white_die + _red_die; }
		}
		public EVENTS Event {
			get { return _event; }
		}
		public String Hex {
			get { return _hex; }
		}
		public Nationality Nation {
			get { return _nation; }
		}
		public int Number {
			get { return _number; }
		}
		public ORDERS Order {
			get { return _order; }
		}
		public int Red {
			get { return _red_die; }
		}
		public TRIGGERS Trigger {
			get { return _trigger; }
		}
		public int White {
			get { return _white_die; }
		}

	}


	public class Deck {

		protected List<Card> cards;
		protected Nationality _nation;

		public Deck(Nationality n) {
			_nation = n;
			cards = new List<Card>();
		}

		public Deck() : this(null){

		}

		public int Count {
			get { return cards.Count; }
		}

		public Card Draw() {
			Card c = null;
			if (Count > 0) {
				int x = Randomizer.get(0, Count-1);
				c = cards[x];
				cards.RemoveAt(x);
			}
			else
				throw new EmptyDeckException(String.Format("Attempt by {0} to draw from empty deck", _nation.ToString()));
			return c;
		}

		public void Add(Card c) {
			cards.Add(c);
		}

		//"shuffles" deck d into this deck and leaves d empty
		public void ShuffleInto(Deck d) {
			cards.AddRange(d.cards);
			d.cards = new List<Card>();
		}

		public class EmptyDeckException : System.ApplicationException {
			public EmptyDeckException() : base() { }
			public EmptyDeckException(string message) : base(message) { }
			public EmptyDeckException(string message, System.Exception inner) : base(message, inner) { }
		}
	}
	public sealed class AmericanDeck : Deck {
		public AmericanDeck(Nationality n)
			: base(n) {

			Add(new Card(_nation, 1, ORDERS.FIRE, ACTIONS.ASSAULT_FIRE, EVENTS.SHELLHOLES, "A2", 1, 1, TRIGGERS.JAMMED));
			Add(new Card(_nation, 2, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.BOOBY_TRAP, "A4", 1, 1, TRIGGERS.JAMMED));
			Add(new Card(_nation, 3, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.RUBBLE, "A6", 1, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 4, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.DUST, "A8", 1, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 5, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.MISSION_OBJECTIVE, "B2", 2, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 6, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.STRATEGIC_OBJECTIVE, "B4", 2, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 7, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.MEDIC, "B6", 1, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 8, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.KIA, "B8", 1, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 9, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.AIR_SUPPORT, "B10", 2, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 10, ORDERS.COMMAND_CONFUSION, ACTIONS.SPRAY_FIRE, EVENTS.SHELL_SHOCK, "C2", 2, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 11, ORDERS.ROUT, ACTIONS.SPRAY_FIRE, EVENTS.ELAN, "C4", 3, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 12, ORDERS.ROUT, ACTIONS.SPRAY_FIRE, EVENTS.ELAN, "C6", 3, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 13, ORDERS.ROUT, ACTIONS.HAND_GRENADES, EVENTS.BREEZE, "C8", 1, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 14, ORDERS.ROUT, ACTIONS.HAND_GRENADES, EVENTS.BREEZE, "C10", 1, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 15, ORDERS.ROUT, ACTIONS.HAND_GRENADES, EVENTS.BREEZE, "D2", 2, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 16, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D4", 2, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 17, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D6", 3, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 18, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D8", 3, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 19, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.AIR_SUPPORT, "D10", 4, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 20, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.AIR_SUPPORT, "E2", 4, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 21, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.FOG_OF_WAR, "E4", 1, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 22, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.WHITE_PHOSPHORUS, "E6", 1, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 23, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.WHITE_PHOSPHORUS, "E8", 2, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 24, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.WHITE_PHOSPHORUS, "E10", 2, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 25, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.FIELD_PROMOTION, "F2", 3, 3, TRIGGERS.SNIPER));
			Add(new Card(_nation, 26, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.RECONNAISSANCE, "F4", 3, 3, TRIGGERS.SNIPER));
			Add(new Card(_nation, 27, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.RECONNAISSANCE, "F6", 4, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 28, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.DEPLOY, "F8", 4, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 29, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.DEPLOY, "F10", 5, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 30, ORDERS.ROUT, ACTIONS.SUSTAINED_FIRE, EVENTS.DEPLOY, "G2", 5, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 31, ORDERS.ARTILLERY_DENIED, ACTIONS.HIDDEN_UNIT, EVENTS.INTERDICTION, "G4", 1, 6, TRIGGERS.EVENT));
			Add(new Card(_nation, 32, ORDERS.ARTILLERY_DENIED, ACTIONS.HIDDEN_MINES, EVENTS.INTERDICTION, "G6", 1, 6, TRIGGERS.EVENT));
			Add(new Card(_nation, 33, ORDERS.ARTILLERY_DENIED, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "G8", 2, 5, TRIGGERS.EVENT));
			Add(new Card(_nation, 34, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "G10", 2, 5, TRIGGERS.EVENT));
			Add(new Card(_nation, 35, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "H2", 3, 4, TRIGGERS.EVENT));
			Add(new Card(_nation, 36, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "H4", 3, 4, TRIGGERS.EVENT));
			Add(new Card(_nation, 37, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_ENTRENCHMENTS, EVENTS.SAPPERS, "H6", 4, 3, TRIGGERS.EVENT));
			Add(new Card(_nation, 38, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_ENTRENCHMENTS, EVENTS.SAPPERS, "H8", 4, 3, TRIGGERS.EVENT));
			Add(new Card(_nation, 39, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_ENTRENCHMENTS, EVENTS.BATTLEFIELD_INTEGRITY, "I2", 5, 2, TRIGGERS.EVENT));
			Add(new Card(_nation, 40, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_WIRE, EVENTS.SUPPRESSING_FIRE, "I4", 5, 2, TRIGGERS.EVENT));
			Add(new Card(_nation, 41, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_WIRE, EVENTS.SUPPRESSING_FIRE, "I6", 6, 1, TRIGGERS.EVENT));
			Add(new Card(_nation, 42, ORDERS.ARTILLERY_REQUEST, ACTIONS.BORE_SIGHTING, EVENTS.SUPPRESSING_FIRE, "I8", 6, 1, TRIGGERS.EVENT));
			Add(new Card(_nation, 43, ORDERS.COMMAND_CONFUSION, ACTIONS.SUSTAINED_FIRE, EVENTS.COMMAND_AND_CONTROL, "I10", 2, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 44, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.BATTLEFIELD_INTEGRITY, "J2", 2, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 45, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.FOG_OF_WAR, "J4", 3, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 46, ORDERS.ADVANCE, ACTIONS.LIGHT_WOUNDS, EVENTS.INTERROGATION, "J6", 3, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 47, ORDERS.ADVANCE, ACTIONS.LIGHT_WOUNDS, EVENTS.INTERROGATION, "J8", 4, 4, TRIGGERS.SNIPER));
			Add(new Card(_nation, 48, ORDERS.MOVE, ACTIONS.LIGHT_WOUNDS, EVENTS.INTERROGATION, "J10", 4, 4, TRIGGERS.SNIPER));
			Add(new Card(_nation, 49, ORDERS.COMMAND_CONFUSION, ACTIONS.SUSTAINED_FIRE, EVENTS.COMMAND_AND_CONTROL, "K2", 5, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 50, ORDERS.COMMAND_CONFUSION, ACTIONS.COMMAND_CONFUSION, EVENTS.MALFUNCTION, "K4", 5, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 51, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.WALKING_WOUNDED, "K6", 6, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 52, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.WALKING_WOUNDED, "K8", 6, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 53, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.WALKING_WOUNDED, "K10", 3, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 54, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.REINFORCEMENTS, "L2", 3, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 55, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.REINFORCEMENTS, "L4", 4, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 56, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.REINFORCEMENTS, "L6", 4, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 57, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.SCROUNGE, "L8", 5, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 58, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.SCROUNGE, "L10", 5, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 59, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M2", 6, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 60, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M4", 6, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 61, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M6", 4, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 62, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M8", 4, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 63, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M10", 5, 5, TRIGGERS.SNIPER));
			Add(new Card(_nation, 64, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.COWER, "N2", 5, 5, TRIGGERS.SNIPER));
			Add(new Card(_nation, 65, ORDERS.FIRE, ACTIONS.LIGHT_WOUNDS, EVENTS.COWER, "N4", 6, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 66, ORDERS.FIRE, ACTIONS.LIGHT_WOUNDS, EVENTS.PRISONERS_OF_WAR, "N6", 6, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 67, ORDERS.FIRE, ACTIONS.DEMOLITIONS, EVENTS.PRISONERS_OF_WAR, "N8", 5, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 68, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.HERO, "N10", 5, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 69, ORDERS.FIRE, ACTIONS.LIGHT_WOUNDS, EVENTS.HERO, "O2", 6, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 70, ORDERS.COMMAND_CONFUSION, ACTIONS.COMMAND_CONFUSION, EVENTS.HERO, "O4", 6, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 71, ORDERS.COMMAND_CONFUSION, ACTIONS.SUSTAINED_FIRE, EVENTS.HERO, "O6", 6, 6, TRIGGERS.TIME));
			Add(new Card(_nation, 72, ORDERS.COMMAND_CONFUSION, ACTIONS.CROSSFIRE, EVENTS.HERO, "O10", 6, 6, TRIGGERS.TIME));

		}
	}
	public sealed class GermanDeck : Deck {
		public GermanDeck(Nationality n)
			: base(n) {

			Add(new Card(_nation, 1, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.SHELLHOLES, "A3", 1, 1, TRIGGERS.JAMMED));
			Add(new Card(_nation, 2, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.BOOBY_TRAP, "A5", 1, 1, TRIGGERS.JAMMED));
			Add(new Card(_nation, 3, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.RUBBLE, "A7", 1, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 4, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.DUST, "A9", 1, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 5, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.MISSION_OBJECTIVE, "B1", 2, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 6, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.STRATEGIC_OBJECTIVE, "B3", 2, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 7, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.MEDIC, "B5", 1, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 8, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.KIA, "B7", 1, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 9, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.AIR_SUPPORT, "B9", 2, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 10, ORDERS.ROUT, ACTIONS.SPRAY_FIRE, EVENTS.SHELL_SHOCK, "C1", 2, 2, TRIGGERS.SNIPER));
			Add(new Card(_nation, 11, ORDERS.ROUT, ACTIONS.SPRAY_FIRE, EVENTS.ELAN, "C3", 3, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 12, ORDERS.ROUT, ACTIONS.SPRAY_FIRE, EVENTS.ELAN, "C5", 3, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 13, ORDERS.ROUT, ACTIONS.HAND_GRENADES, EVENTS.BREEZE, "C7", 1, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 14, ORDERS.ROUT, ACTIONS.HAND_GRENADES, EVENTS.BREEZE, "C9", 1, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 15, ORDERS.ROUT, ACTIONS.HAND_GRENADES, EVENTS.BREEZE, "D1", 2, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 16, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D3", 2, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 17, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D5", 3, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 18, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D7", 3, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 19, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.BLAZE, "D9", 4, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 20, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.BLAZE, "E1", 4, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 21, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.BLAZE, "E3", 1, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 22, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.BLAZE, "E5", 1, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 23, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.BLAZE, "E7", 2, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 24, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.BLAZE, "E9", 2, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 25, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.FIELD_PROMOTION, "F1", 3, 3, TRIGGERS.SNIPER));
			Add(new Card(_nation, 26, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.RECONNAISSANCE, "F3", 3, 3, TRIGGERS.SNIPER));
			Add(new Card(_nation, 27, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.RECONNAISSANCE, "F5", 4, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 28, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.DEPLOY, "F7", 4, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 29, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.DEPLOY, "F9", 5, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 30, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.DEPLOY, "G1", 5, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 31, ORDERS.COMMAND_CONFUSION, ACTIONS.HIDDEN_UNIT, EVENTS.INTERDICTION, "G3", 1, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 32, ORDERS.ARTILLERY_DENIED, ACTIONS.HIDDEN_MINES, EVENTS.INTERDICTION, "G5", 1, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 33, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "G7", 2, 5, TRIGGERS.EVENT));
			Add(new Card(_nation, 34, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "G9", 2, 5, TRIGGERS.EVENT));
			Add(new Card(_nation, 35, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "H3", 3, 4, TRIGGERS.EVENT));
			Add(new Card(_nation, 36, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "H5", 3, 4, TRIGGERS.EVENT));
			Add(new Card(_nation, 37, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_ENTRENCHMENTS, EVENTS.SAPPERS, "H7", 4, 3, TRIGGERS.EVENT));
			Add(new Card(_nation, 38, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_ENTRENCHMENTS, EVENTS.SAPPERS, "H9", 4, 3, TRIGGERS.EVENT));
			Add(new Card(_nation, 39, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_PILLBOX, EVENTS.BATTLEFIELD_INTEGRITY, "I1", 5, 2, TRIGGERS.EVENT));
			Add(new Card(_nation, 40, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_WIRE, EVENTS.SUPPRESSING_FIRE, "I3", 5, 2, TRIGGERS.EVENT));
			Add(new Card(_nation, 41, ORDERS.ARTILLERY_DENIED, ACTIONS.HIDDEN_WIRE, EVENTS.SUPPRESSING_FIRE, "I5", 6, 1, TRIGGERS.EVENT));
			Add(new Card(_nation, 42, ORDERS.COMMAND_CONFUSION, ACTIONS.BORE_SIGHTING, EVENTS.SUPPRESSING_FIRE, "I7", 6, 1, TRIGGERS.EVENT));
			Add(new Card(_nation, 43, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.COMMAND_AND_CONTROL, "I9", 2, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 44, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.BATTLEFIELD_INTEGRITY, "J1", 2, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 45, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.AIR_SUPPORT, "J3", 3, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 46, ORDERS.COMMAND_CONFUSION, ACTIONS.LIGHT_WOUNDS, EVENTS.INTERROGATION, "J5", 3, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 47, ORDERS.COMMAND_CONFUSION, ACTIONS.COMMAND_CONFUSION, EVENTS.INTERROGATION, "J7", 4, 4, TRIGGERS.SNIPER));
			Add(new Card(_nation, 48, ORDERS.ROUT, ACTIONS.CONCEALMENT, EVENTS.INTERROGATION, "J9", 4, 4, TRIGGERS.SNIPER));
			Add(new Card(_nation, 49, ORDERS.COMMAND_CONFUSION, ACTIONS.SUSTAINED_FIRE, EVENTS.COMMAND_AND_CONTROL, "K1", 5, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 50, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.MALFUNCTION, "K3", 5, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 51, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.WALKING_WOUNDED, "K5", 6, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 52, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.WALKING_WOUNDED, "K7", 6, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 53, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.WALKING_WOUNDED, "K9", 3, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 54, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.INFILTRATION, "L1", 3, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 55, ORDERS.FIRE, ACTIONS.SMOKE_GRENADES, EVENTS.REINFORCEMENTS, "L3", 4, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 56, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.REINFORCEMENTS, "L5", 4, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 57, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.SCROUNGE, "L7", 5, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 58, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "L9", 5, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 59, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M1", 6, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 60, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M3", 6, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 61, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M5", 4, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 62, ORDERS.FIRE, ACTIONS.NO_QUARTER, EVENTS.BATTLE_HARDEN, "M7", 4, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 63, ORDERS.FIRE, ACTIONS.NO_QUARTER, EVENTS.COWER, "M9", 5, 5, TRIGGERS.SNIPER));
			Add(new Card(_nation, 64, ORDERS.FIRE, ACTIONS.NO_QUARTER, EVENTS.COWER, "N1", 5, 5, TRIGGERS.SNIPER));
			Add(new Card(_nation, 65, ORDERS.FIRE, ACTIONS.DEMOLITIONS, EVENTS.PRISONERS_OF_WAR, "N3", 6, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 66, ORDERS.FIRE, ACTIONS.LIGHT_WOUNDS, EVENTS.PRISONERS_OF_WAR, "N5", 6, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 67, ORDERS.FIRE, ACTIONS.LIGHT_WOUNDS, EVENTS.HERO, "N7", 5, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 68, ORDERS.ADVANCE, ACTIONS.LIGHT_WOUNDS, EVENTS.HERO, "N9", 5, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 69, ORDERS.ADVANCE, ACTIONS.LIGHT_WOUNDS, EVENTS.HERO, "O3", 6, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 70, ORDERS.COMMAND_CONFUSION, ACTIONS.MARKSMANSHIP, EVENTS.HERO, "O5", 6, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 71, ORDERS.COMMAND_CONFUSION, ACTIONS.SUSTAINED_FIRE, EVENTS.HERO, "O7", 6, 6, TRIGGERS.TIME));
			Add(new Card(_nation, 72, ORDERS.COMMAND_CONFUSION, ACTIONS.SUSTAINED_FIRE, EVENTS.FOG_OF_WAR, "O9", 6, 6, TRIGGERS.TIME));
		}
	}
	public sealed class RussianDeck : Deck {
		public RussianDeck(Nationality n)
			: base(n) {

			Add(new Card(_nation, 1, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.SHELLHOLES, "A2", 1, 1, TRIGGERS.JAMMED));
			Add(new Card(_nation, 2, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.BOOBY_TRAP, "A4", 1, 1, TRIGGERS.JAMMED));
			Add(new Card(_nation, 3, ORDERS.RECOVER, ACTIONS.ASSAULT_FIRE, EVENTS.RUBBLE, "A6", 1, 2, TRIGGERS.JAMMED));
			Add(new Card(_nation, 4, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.DUST, "A8", 1, 2, TRIGGERS.JAMMED));
			Add(new Card(_nation, 5, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.MISSION_OBJECTIVE, "B2", 2, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 6, ORDERS.RECOVER, ACTIONS.HAND_GRENADES, EVENTS.STRATEGIC_OBJECTIVE, "B4", 2, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 7, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.MEDIC, "B6", 1, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 8, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.KIA, "B8", 1, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 9, ORDERS.RECOVER, ACTIONS.SPRAY_FIRE, EVENTS.AIR_SUPPORT, "B10", 2, 2, TRIGGERS.SNIPER));
			Add(new Card(_nation, 10, ORDERS.MOVE, ACTIONS.SPRAY_FIRE, EVENTS.SHELL_SHOCK, "C2", 2, 2, TRIGGERS.SNIPER));
			Add(new Card(_nation, 11, ORDERS.ROUT, ACTIONS.SPRAY_FIRE, EVENTS.ELAN, "C4", 3, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 12, ORDERS.ROUT, ACTIONS.SPRAY_FIRE, EVENTS.ELAN, "C6", 3, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 13, ORDERS.ROUT, ACTIONS.DEMOLITIONS, EVENTS.BREEZE, "C8", 1, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 14, ORDERS.ROUT, ACTIONS.SUSTAINED_FIRE, EVENTS.BREEZE, "C10", 1, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 15, ORDERS.ROUT, ACTIONS.SUSTAINED_FIRE, EVENTS.BREEZE, "D2", 2, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 16, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D4", 2, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 17, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D6", 3, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 18, ORDERS.ROUT, ACTIONS.ASSAULT_FIRE, EVENTS.BREEZE, "D8", 3, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 19, ORDERS.ROUT, ACTIONS.CROSSFIRE, EVENTS.COMMISSAR, "D10", 4, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 20, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.COMMISSAR, "E2", 4, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 21, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.COMMISSAR, "E4", 1, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 22, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.COMMISSAR, "E6", 1, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 23, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.ENTRENCH, "E8", 2, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 24, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.ENTRENCH, "E10", 2, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 25, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.FIELD_PROMOTION, "F2", 3, 3, TRIGGERS.SNIPER));
			Add(new Card(_nation, 26, ORDERS.MOVE, ACTIONS.CROSSFIRE, EVENTS.RECONNAISSANCE, "F4", 3, 3, TRIGGERS.SNIPER));
			Add(new Card(_nation, 27, ORDERS.MOVE, ACTIONS.CONCEALMENT, EVENTS.RECONNAISSANCE, "F6", 4, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 28, ORDERS.ADVANCE, ACTIONS.SMOKE_GRENADES, EVENTS.FOG_OF_WAR, "F8", 4, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 29, ORDERS.ADVANCE, ACTIONS.SMOKE_GRENADES, EVENTS.FOG_OF_WAR, "F10", 5, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 30, ORDERS.COMMAND_CONFUSION, ACTIONS.SMOKE_GRENADES, EVENTS.FOG_OF_WAR, "G2", 5, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 31, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_UNIT, EVENTS.INTERDICTION, "G4", 1, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 32, ORDERS.ARTILLERY_DENIED, ACTIONS.HIDDEN_MINES, EVENTS.INTERDICTION, "G6", 1, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 33, ORDERS.COMMAND_CONFUSION, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "G8", 2, 5, TRIGGERS.EVENT));
			Add(new Card(_nation, 34, ORDERS.COMMAND_CONFUSION, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "G10", 2, 5, TRIGGERS.EVENT));
			Add(new Card(_nation, 35, ORDERS.COMMAND_CONFUSION, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "H2", 3, 4, TRIGGERS.EVENT));
			Add(new Card(_nation, 36, ORDERS.ARTILLERY_REQUEST, ACTIONS.DIG_IN, EVENTS.INTERDICTION, "H4", 3, 4, TRIGGERS.EVENT));
			Add(new Card(_nation, 37, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_ENTRENCHMENTS, EVENTS.SAPPERS, "H6", 4, 3, TRIGGERS.EVENT));
			Add(new Card(_nation, 38, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_ENTRENCHMENTS, EVENTS.SAPPERS, "H8", 4, 3, TRIGGERS.EVENT));
			Add(new Card(_nation, 39, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_PILLBOX, EVENTS.BATTLEFIELD_INTEGRITY, "I2", 5, 2, TRIGGERS.EVENT));
			Add(new Card(_nation, 40, ORDERS.ARTILLERY_REQUEST, ACTIONS.HIDDEN_WIRE, EVENTS.SUPPRESSING_FIRE, "I4", 5, 2, TRIGGERS.EVENT));
			Add(new Card(_nation, 41, ORDERS.ARTILLERY_DENIED, ACTIONS.HIDDEN_WIRE, EVENTS.SUPPRESSING_FIRE, "I6", 6, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 42, ORDERS.ARTILLERY_DENIED, ACTIONS.BORE_SIGHTING, EVENTS.SUPPRESSING_FIRE, "I8", 6, 1, TRIGGERS.NONE));
			Add(new Card(_nation, 43, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.COMMAND_AND_CONTROL, "I10", 2, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 44, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.BATTLEFIELD_INTEGRITY, "J2", 2, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 45, ORDERS.ADVANCE, ACTIONS.SUSTAINED_FIRE, EVENTS.AIR_SUPPORT, "J4", 3, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 46, ORDERS.ADVANCE, ACTIONS.LIGHT_WOUNDS, EVENTS.INTERROGATION, "J6", 3, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 47, ORDERS.MOVE, ACTIONS.LIGHT_WOUNDS, EVENTS.INTERROGATION, "J8", 4, 4, TRIGGERS.SNIPER));
			Add(new Card(_nation, 48, ORDERS.MOVE, ACTIONS.LIGHT_WOUNDS, EVENTS.INTERROGATION, "J10", 4, 4, TRIGGERS.SNIPER));
			Add(new Card(_nation, 49, ORDERS.MOVE, ACTIONS.LIGHT_WOUNDS, EVENTS.COMMAND_AND_CONTROL, "K2", 5, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 50, ORDERS.MOVE, ACTIONS.LIGHT_WOUNDS, EVENTS.MALFUNCTION, "K4", 5, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 51, ORDERS.COMMAND_CONFUSION, ACTIONS.LIGHT_WOUNDS, EVENTS.WALKING_WOUNDED, "K6", 6, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 52, ORDERS.FIRE, ACTIONS.LIGHT_WOUNDS, EVENTS.WALKING_WOUNDED, "K8", 6, 2, TRIGGERS.NONE));
			Add(new Card(_nation, 53, ORDERS.FIRE, ACTIONS.SUSTAINED_FIRE, EVENTS.WALKING_WOUNDED, "K10", 3, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 54, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.INFILTRATION, "L2", 3, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 55, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.INFILTRATION, "L4", 4, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 56, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.REINFORCEMENTS, "L6", 4, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 57, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.SCROUNGE, "L8", 5, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 58, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "L10", 5, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 59, ORDERS.FIRE, ACTIONS.AMBUSH, EVENTS.BATTLE_HARDEN, "M2", 6, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 60, ORDERS.FIRE, ACTIONS.NO_QUARTER, EVENTS.BATTLE_HARDEN, "M4", 6, 3, TRIGGERS.NONE));
			Add(new Card(_nation, 61, ORDERS.FIRE, ACTIONS.NO_QUARTER, EVENTS.COWER, "M6", 4, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 62, ORDERS.FIRE, ACTIONS.NO_QUARTER, EVENTS.COWER, "M8", 4, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 63, ORDERS.FIRE, ACTIONS.LIGHT_WOUNDS, EVENTS.COWER, "M10", 5, 5, TRIGGERS.SNIPER));
			Add(new Card(_nation, 64, ORDERS.FIRE, ACTIONS.CONCEALMENT, EVENTS.COWER, "N2", 5, 5, TRIGGERS.SNIPER));
			Add(new Card(_nation, 65, ORDERS.FIRE, ACTIONS.CONCEALMENT, EVENTS.PRISONERS_OF_WAR, "N4", 6, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 66, ORDERS.FIRE, ACTIONS.CONCEALMENT, EVENTS.PRISONERS_OF_WAR, "N6", 6, 4, TRIGGERS.NONE));
			Add(new Card(_nation, 67, ORDERS.FIRE, ACTIONS.CONCEALMENT, EVENTS.PRISONERS_OF_WAR, "N8", 5, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 68, ORDERS.FIRE, ACTIONS.CONCEALMENT, EVENTS.PRISONERS_OF_WAR, "N10", 5, 6, TRIGGERS.NONE));
			Add(new Card(_nation, 69, ORDERS.FIRE, ACTIONS.CONCEALMENT, EVENTS.HERO, "O2", 6, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 70, ORDERS.COMMAND_CONFUSION, ACTIONS.HAND_GRENADES, EVENTS.HERO, "O4", 6, 5, TRIGGERS.NONE));
			Add(new Card(_nation, 71, ORDERS.COMMAND_CONFUSION, ACTIONS.HAND_GRENADES, EVENTS.ENTRENCH, "O6", 6, 6, TRIGGERS.TIME));
			Add(new Card(_nation, 72, ORDERS.COMMAND_CONFUSION, ACTIONS.HAND_GRENADES, EVENTS.ENTRENCH, "O10", 6, 6, TRIGGERS.TIME));
		}
	}

}
